Name=lliurex-up
Name[en]=LliureX Upgrader
Name[es]=Actualizador de LliureX
Name[qcv]=Actualitzador de LliureX
Name[ca_ES]=Actualitzador de LliureX
Name[ca_ES.UTF-8]=Actualitzador de LliureX
Name[ca_ES@valencia]=Actualitzador de LliureX
Comment=LliureX Upgrader
Comment[es]=Actualizacion de la versión Lliurex 19
Comment[qcv]=Actualitzador de la versió del LliureX 19
Comment[ca_ES]=Actualitzador de la versió del LliureX 19
Comment[ca_ES@valencia]=Actualitzador de la versió del LliureX 19
Icon=lliurex-up
Category=System
ScriptPath=lliurex-up.zmd
Service=False
Using=pkexec
Groups=sudo;admins
