#!/bin/bash
ACTION="$1"
case "$ACTION" in 
	preActions)
		{ dpkg-divert --list /usr/sbin/update-initramfs | grep -q lliurex-up ; } || dpkg-divert --quiet --add --divert /usr/sbin/update-initramfs.REAL --package lliurex-up --rename /usr/sbin/update-initramfs
		if [ ! -L /usr/sbin/update-initramfs ]; then
			ln -s /usr/lib/lliurex-up/update-initramfs-alternative /usr/sbin/update-initramfs
		fi
	;;
	postActions)
		rc=0
		dpkg-divert --list /usr/sbin/update-initramfs | grep -q lliurex-up && rc=1
		if [ "$rc" = "1" ]; then
			rm /usr/sbin/update-initramfs
			dpkg-divert --quiet --remove --rename /usr/sbin/update-initramfs
		fi
	;;
esac
